- .firebaserc
- firebase.json
- functions/.gitignore
- functions/package-lock.json
- functions/package.json
- functions/src/index.ts
- functions/tsconfig.json
- functions/tslint.json
- tsconfig.json
firebase functionsをTypeScriptでプロジェクトにインストールしました。
> [ADD]firebase functionsのインストール

- components/inputs/adultInput.vue
- stories/input.stories.js
> [ADD]adultInputの作成

- components/buttons/backButton.vue
- stories/button.stories.js
> Michi back button

- components/buttons/goToWatchButton.vue
- stories/button.stories.js
goToWatchButtonを作成しました。
- scssのmediaqueryのところ（レスポンシブ化する時のピクセルの値）
- storybookに追加しているところ
> [ADD]goToWatchButton作成

- components/buttons/nextButton.vue
- stories/button.stories.js
developから新しくブランチ切りました、おねがいします！
> Michi next button

- components/selector/movieTheaterSelector.vue
- stories/selector.stories.js
> [ADD]movieTheaterSelectorの作成

- components/buttons/seatButton.vue
- stories/button.stories.js
> Michi seat button

- components/selector/secretGenreSelector.vue
- stories/selector.stories.js
> secretGenreSelectorの作成

- components/buttons/tabButton.vue
- layouts/tabs/movieDetailsTab.vue
- stories/layout.stories.js
> Michi movie details tab

- components/marks/reservedSeatMark.vue
- stories/mark.stories.js
> Michi reserved seat mark

- components/buttons/tabButton.vue
> [UPDATE] tabButtonwo

- components/buttons/closeButton.vue
> [UPDATE]closeButtonレスポンシブ化

- components/buttons/tagButton.vue
> [UPDATE]レスポンシブ化

- components/buttons/nextButton.vue
> [UPDATE]レスポンシブNextButton

- components/marks/reservedSeatMark.vue
> [UPDATE]reservedsertmarkをレスポンシブ化

- components/buttons/seatButton.vue
> [UPDATE]sertButtonレスポンシブ化

- components/buttons/hintButton.vue
- pages/michi_hintDammy.vue
> Michi hint button

- components/selector/creditCardMonth.vue
> Responsib Credit Card Month

- components/texts/screeningYear.vue
> Responsib ScreeingYear

- components/selector/peopleInput.vue
> [UPDATE]responsivePeopleInput

- components/buttons/tabButton.vue
- components/texts/movieTitle.vue
- layouts/tabs/movieDetailsTab.vue
- pages/movies/_id.vue
> Michi respons id vue

- components/buttons/paymentButton.vue
> michi Respons Payment Button

- components/inputs/creditCardDate.vue
> Responsib Credit Card Date
